### ISSUE TITLE
Error with einsum in Equivariance plot

### ISSUE THREAD

**Issue by SkirOwen** [jonas-koehler/s2cnn#54]
Hello,

I'm trying to run the equivariance_plot but come up with this error, I am using `CUDA 11` with pytorch and cupy for cuda 11:

```python
 File "/home/owen/anaconda3/envs/s2cnn/lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: expected scalar type Float but found ComplexFloat
```

Full error log:
```python
runfile('/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot/main.py', wdir='/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot')
/home/owen/anaconda3/envs/s2cnn/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
compute 0.pkl.gz... save 0.pkl.gz... done
compute 0.pkl.gz... save 0.pkl.gz... done
Traceback (most recent call last):
  File "/home/owen/anaconda3/envs/s2cnn/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-34cedf137222>", line 1, in <module>
    runfile('/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot/main.py', wdir='/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot')
  File "/home/owen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.7142.13/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/owen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.7142.13/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot/main.py", line 102, in <module>
    main()
  File "/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot/main.py", line 76, in main
    y1 = phi(s2_rotation(x, *abc))
  File "/home/owen/PycharmProjects/s2cnn/examples/equivariance_plot/main.py", line 14, in s2_rotation
    x = so3_rotation(x.view(*x.size(), 1).expand(*x.size(), x.size(-1)), a, b, c)
  File "/home/owen/PycharmProjects/s2cnn/s2cnn/soft/so3_rotation.py", line 21, in so3_rotation
    x = SO3_fft_real.apply(x)  # [l * m * n, ..., complex]
  File "/home/owen/PycharmProjects/s2cnn/s2cnn/soft/so3_fft.py", line 453, in forward
    return so3_rfft(x, b_out=ctx.b_out)
  File "/home/owen/PycharmProjects/s2cnn/s2cnn/soft/so3_fft.py", line 110, in so3_rfft
    out = torch.einsum("bmn,zbmnc->mnzc", (wigner[:, s].view(-1, 2 * l + 1, 2 * l + 1), xx))
  File "/home/owen/anaconda3/envs/s2cnn/lib/python3.8/site-packages/torch/functional.py", line 342, in einsum
    return einsum(equation, *_operands)
  File "/home/owen/anaconda3/envs/s2cnn/lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: expected scalar type Float but found ComplexFloat
```

**Comment by mariogeiger** [comment]
I guess the error was introduced in https://github.com/jonas-koehler/s2cnn/pull/51 since I guessed the Fourier transform from pytorch changed the format of the output by a little. 

I don't have the time to deep into this now. PR are welcome. In case you look for similar features (Fourier transform on the sphere) have a look at the project e3nn that is maintained.

**Comment by SkirOwen** [comment]
I've found this:
[https://github.com/pytorch/pytorch/wiki/The-torch.fft-module-in-PyTorch-1.7](url)

**Comment by SkirOwen** [comment]
I've found a temporary fix, that works for me:

If you have `pytorch == 1.7.*`:

- change all functions of the form `pytorch.fft.____` to `pytorch.Tensor.____`

If `pytorch >= 1.7` then follow:

- [https://github.com/pytorch/pytorch/wiki/The-torch.fft-module-in-PyTorch-1.7](url)
